### ISSUE TITLE
Add a new CLI command to build model

### ISSUE THREAD

**Issue by rafiahmedd** [CodesVault/kathamo-generator#2]
Model is a necessary part of any application, I think it will be good to add a command for building model.

**Comment by rafiahmedd** [comment]
Pull request added.

https://github.com/CodesVault/kathamo-generator/pull/3

**Comment by AbmSourav** [comment]
Hey @rafiahmedd ,  We are not using ORM in the framework, that's why currently we are not introducing Models in the architecture. #3 
Thanks for your time and interest.  And hopefully, you'll keep exploring [Kathamo](https://kathamo.dev).
